version: "3.9"

services:
  web:
    image: makhimkitov/app2:v1
    volumes:
      - .:/code
    ports:
      - "9000:9000"
    links:
      - redis
      - celery
  redis:
    image: redis
  celery:
    image: celery

    command: celery -b redis -a hw6
