# Generated by Django 3.1.3 on 2020-12-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Названия существа')),
                ('level', models.IntegerField(verbose_name='Уровень существа')),
                ('descr', models.TextField(verbose_name='писание существа')),
            ],
        ),
    ]
